### PR TITLE
LEARNING GITHUB

### PR DESCRIPTION
**Pull request by kingbass01**

### CODE REVIEW

**Comment by PrajjuS** [comment]
How u so pero?

**Comment by kingbass01** [comment]
> How u so pero?

Cause u
Wen teach

**Comment by PrajjuS** [comment]
> 

Nu uuuu

**Comment by PrajjuS** [comment]
> > How u so pero?
> 
> Cause u Wen teach

Nuu uuuuuuuu

**Comment by kingbass01** [comment]
> > > How u so pero?
> > 
> > 
> > Cause u Wen teach
> 
> Nuu uuuuuuuu
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Pull request closed without merging**
